name: Jira Find multiple issue keys
description: Find an issue inside event
branding:
  icon: 'book-open'
  color: 'blue'
inputs:
  string:
    description: Provide a string to extract issue key from
    required: false
  from:
    description: Find from predefined place (should be either 'branch', or 'commits')
    required: false
    default: commits
outputs:
  issue:
    description: Keys of the found issue
runs:
  using: 'node16'
  main: './dist/index.js'
